### PR TITLE
New rmf-codegen based api

### PR DESCRIPTION
**Pull request by mvantellingen**
This PR will be serving as the new 1.0 API for commercetools. The biggest change is that this removes our own code generator by replacing it with the commercetools maintained [rmf-codegen](https://github.com/commercetools/rmf-codegen) project.

Previously we tried to make the API as Go idiomatic as possible. This was quite a challenge when auto-generating the API based on specifications. It also made is almost impossible to support the new API's like importapi, machine-learning and history offered by commercetools. 

For this reason the new version uses the same command builder pattern used by other API's for commercetools. This means that the Client is significantly changed and no longer backwards compatible The actual models (structs) should still behave the same.

For the code generator, see: https://github.com/commercetools/rmf-codegen/pull/219

### CODE REVIEW

**Comment by Multiply** [comment]
Is there anything we can help with, to speed up the development here, or in the rmf-codegen?

**Comment by mvantellingen** [comment]
Hi @Multiply, it's currently hanging on a decision I need to make regarding API design. Perhaps you can give your opinion about this.

So the basic pattern will be something like this: `client.WithProjectKey("my-project").Products().Get()` or `client.WithProjectKey("my-project").Products().Post(&draft)` In that sense it follows all the other commercetools sdk's and we are 'safe' regarding new endpoints that will be added by commercetools.

Now to pass query parameters and headers I was thinking about using the functional options pattern.

```golang
request := (client.
    WithProjectKey("my-project").
    Products().
    Get(
	commercetools.WithQueryParams(&platform.ByProjectKeyProductsRequestMethodGetInput{
		Limit:  Int(10),
		Offset: Int(20),
		Expand: []string{"foobar"},
	}),
	commercetools.WithHeaders(map[string]string{
		"foo": "bar",
	}),
    ))
```

An alternative is something like

```golang
request := (client.
    WithProjectKey("my-project").
    Products().
    Get().
    WithQueryParams(&platform.ByProjectKeyProductsRequestMethodGetInput{
        Limit:  Int(10),
        Offset: Int(20),
        Expand: []string{"foobar"},
    }).
    WithHeaders(map[string]string{
        "foo": "bar",
    }),
    .Execute())    
```

For the first version I think we need Generics support or do something with reflection.

**Comment by Multiply** [comment]
**Pattern**
Personally, I'm not a fan of chaining all too much, but I'm not opposed to it either.
I'd probably go with the former, but move it out of the .Get call, as that seems more of a routing thing, and after you done fully routing, you start tweaking your call.
What is the plan for post/put bodies?

**Headers**
I'd say for headers, you're probably better off with interceptors, which can modify the http request directly, and that would also allow other uses, like tracing.
If you want to, you can then provide an easy to use helper specifically for headers.

**Comment by mvantellingen** [comment]
Hi @Multiply,

I've made considerable progress regarding the new SDK. Could you give it a test for me? I'm interested in your feedback.

The approach is to still use method chaining since the commercetools API is built using this pattern and all other commercetools SDK's also implement it this way. We tried using a more Go idiomatic API in the current SDK but we really got stuck there, and supporting the other api's (like importapi) was becoming unfeasible.

I did add support for setting query parameters via methods. An example call:

```go
response, err := client.
    WithProjectKey("unittest").
    ProductProjections().
    Search().
    Get().
    Limit(30).
    Execute(context.TODO())
```

**Comment by Multiply** [comment]
I'll take it for a spin when I get a few minutes of spare time!

@parsaakbari1209 summoning you here. If you have some time to also give your feedback on the new SDK, it would be lovely.

**Pull request merged**
